name: CI

on:
  push:
  pull_request:

jobs:
  build-from-source:
    name: build from source
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        feature: ["build-from-source"]
        build_mode: [""]
        os: [macos-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Install Linux dependencies
        uses: ./.github/actions/install-linux-deps
      - name: Build sdl3
        shell: bash
        env:
          CI_BUILD_FEATURES: "raw-window-handle"
          RUST_TEST_THREADS: 1
        run: |
          set -xeuo pipefail
          rustc --version
          cargo --version
          cargo build --features "${CI_BUILD_FEATURES} ${{ matrix.feature }}" ${{ matrix.build_mode }}
          cargo build --examples --features "${CI_BUILD_FEATURES} ${{ matrix.feature }}" ${{ matrix.build_mode }}

  release:
    name: Tag Release
    needs: build-from-source
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create Release
        id: create_release
        uses: comnoco/create-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
